install:
	pip install --upgrade pip && \
		pip install -r requirements.txt
lint:
	# lint 
	pylint --disable=R,C api/*.py
test:
	# test

build:
	# build container

deploy:
	# deploy

all: install lint test deploy