name: Pull request workflows
on:
  push:
    branches: ["main"]
  pull_requests:
    branches: ["main"]
jobs:
  CI:
    uses: sanbul-solutions/spocity/.github/workflows/reuse_ci.yml@team1
  DeployDev:
    needs: [ci]
    uses: sanbul-solutions/spocity/.github/workflows/reuse_publish.yml@team1
  
  