name: Pull request workflows
on:
  push:
    branches: ["main"]

jobs:
  ci:
    uses: sanbul-solutions/spocity/.github/workflows/reuse_ci.yml@team1
  publish:
    needs: [ci]
    uses: sanbul-solutions/spocity/.github/workflows/reuse_publish.yml@team1
