name: Pull request workflows
on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./streaming
    uses: ./.github/workflows/reuse_install_test_build_run.yml
