name: Resuable workflow to install and test

on:
  workflow_call:

jobs:
  install-test-build-run:
      runs-on: ubuntu-latest
      steps:
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Install dependencies
          run: |
            make install
        - name: Lint with flake8
          run: |
            make lint
        - name: Test with pytest
          run: |
            make test
        - name: Build image
          run: |
            make build
        - name: Run container
          run: |
            make run
        